### ISSUE TITLE
Ethernet trailers break base64 detection

### ISSUE THREAD

**Issue by scotte** [mrash/fwknop#163]
I ran into an interesting issue recently where fwknop wasn't working for me in some circumstances. I think I finally tracked it down to some trailers being injected into the packet along the link (in my case, a "VSS-Monitoring ethernet trailer" source port, which is two bytes at the end of the packet.

This appears to confuse is_base64() -  it looks like it checks the entire data buffer that was sniffed, rather than just the length of the data packet, and as a result fails when it hits the trailer data, which is not valid base64 data.

I'm not sure what is injecting this trailer to the end of the packet, but it seems like fwknop could be a bit smarter about validating the SPA - if it decodes and is complete, that should be sufficient. I need to investigate a bit more what is injecting this trailer, but if it's along the path somewhere and outside of user's control, the only solution might be improving fwknop to handle the (effective) garbage a bit more gracefully.

**Comment by mrash** [comment]
Thanks for reporting this - it is a similar scenario to when the Ethernet FCS (Frame Check Sequence) is added that was fixed according to this code:

https://github.com/mrash/fwknop/blob/master/server/process_packet.c#L143

Maybe fwknopd should always just take the length from the IP header instead of the calculating it from the Ethernet frame. As a test, can you try applying the following one line patch? If this works, I'll fix this up for the 2.6.7 release with a similar strategy:

diff --git a/server/process_packet.c b/server/process_packet.c
index 10467d9..f5f510c 100644
--- a/server/process_packet.c
+++ b/server/process_packet.c
@@ -154,6 +154,8 @@ process_packet(unsigned char *args, const struct pcap_pkthdr *packet_header,
         pkt_end -= FCS_HEADER_LEN;
     }
 
+    pkt_end = (unsigned char*)iph_p + ntohs(iph_p->tot_len);
+
     /* Now, find the packet data payload (depending on IPPROTO).
     */
     src_ip = iph_p->saddr;

**Comment by scotte** [comment]
Thanks, I'll give this a try - seems like a reasonable approach. I wondered why the IP header length wasn't used, but it seemed too obvious so I assumed there was a valid reason it was ignored. :-)

**Comment by scotte** [comment]
Confirmed! Great, looks like this is the problem and the patch works around it. Thanks for the quick reply and patch for testing - gives me a workaround for now.

Thanks again!

**Comment by mrash** [comment]
Great, thanks for the confirmation. This will be fixed in 2.6.7.

**Comment by mrash** [comment]
Fixed in e7b48af4. Thanks.
