### ISSUE TITLE
resolve external ip

### ISSUE THREAD

**Issue by ReubenM** [mrash/fwknop#168]
Just fyi, I noticed fwknop is resolving external ip using a web app you're hosting.
Thought I would mention that you can get it via a DNS lookup:
```bash
dig myip.opendns.com @208.67.220.220 +short
```
The advantage being that it should still work in cases where web traffic might be blocked.

**Comment by mrash** [comment]
Agreed this should be an option. There was some discussion of this feature on the fwknop mailing list as well in this thread:

http://sourceforge.net/p/fwknop/mailman/message/34166016/

I think the default resolution strategy should be via HTTPS since otherwise a MITM attack becomes a lot easier, but still it would be good to have resolution via opendns as an option. And if the user wants to make this the default via a config variable in ~/.fwknoprc that's fine too.

**Comment by rennhak** [comment]
Doesn't work for fwknop via `--resolve-url` but DNS method would be eg. `dig +short myip.opendns.com @resolver1.opendns.com`

**Comment by mrash** [comment]
An easy way to use the dig resolution strategy would be:

fwknop -A tcp/22 -a `dig myip.opendns.com @208.67.220.220 +short` -D serverIP

**Comment by mrash** [comment]
I think the backtics solution is the way to go on this. Closing this issue. If there is a need to build this directly into the client please elaborate and re-open this issue.

**Comment by rennhak** [comment]
Apologies for the delayed answer. Indeed, its a nice solution. Thank your for solving this!
