### ISSUE TITLE
Add support in the access file to include access.d/* folder

### ISSUE THREAD

**Issue by rabin-io** [mrash/fwknop#179]
We can put each file in its own file, making it more manageable, 

This way we can keep the default `access.conf` file clean and have less questions when upgrading/updating the package.

**Comment by oneru** [comment]
There is a current pull request that adds the ability to %include files in access.conf.  That patch doesn't have any wildcard support, but I think that could be added if needed.

An open question: if fwknopd is launched without a access.conf file specified on the command line, it defaults to looking for /etc/access.conf.  Should we also make it default that it grabs any .conf files in "/etc/access.conf.d/" , or is the ability to %include those files sufficient?

**Comment by rabin-io** [comment]
I prefer to have a *single* line in the access.conf, which will look to load all files under `/etc/fwknop/access.conf.d/` and not multi include statements.

As for choosing between a wild card match (*.conf) loading, 
or loading every file under the folder,  I have no preference for one or the other. I just think it's a good option to have.

As for your open question, 
I think you should keep it simple, and only look for a single file.
and let the include statement load the rest of the configuration.

PS. 
put all the files under `/etc/fwknop` and not `/etc/access.conf.d/` as you mention.

**Comment by oneru** [comment]
Yes, typo on my part there, the folder should have been /etc/fwknop/access.conf.d/

**Comment by oneru** [comment]
I'd like to add another access.conf directive, "%includeFolder" that would include the *.conf files in the given directory.  Does this sound about right?

**Comment by rabin-io** [comment]
why not make the `%include` directive to support wild cards? so you can use it like this, 
```
%include "some-defaults.conf"
%include "access.conf.d/*.conf"
%include "access.conf.d/enabled-*.conf"
```

**Comment by oneru** [comment]
As of now, we've opted not to add any regex or wild card matching for the %include directives.  Release 2.6.8 does include both the %include and %include_folder directive, as well as an --access-folder command line option.  The folder options will process any .conf files found in the specified folder.  This should satisfy the initial request.

**Comment by rabin-io** [comment]
thanks :+1: 

(ps. is this ticket is different from ticket #62 ?)

**Comment by mrash** [comment]
Ok, for an access.conf file that is imported from a normal user, fwknopd could enforce either CMD_EXEC_USER or CMD_SUDO_EXEC_USER. Both of these are already supported, so it would be easy to extend them to the open/close cycle stuff. At the same time, fwknopd could also not allow normal users to define commands at all (open/close cycle or otherwise).

**Comment by rabin-io** [comment]
running the command with user privileges, or allowing to use sudo seems the right way.

**Comment by mrash** [comment]
Ok, would you mind opening a new issue for this?

**Comment by oneru** [comment]
CMD_EXEC_USER and CMD_SUDO_EXEC_USER is a great solution; we should certainly pursue that approach.  I would think that CMD_EXEC_USER should be the default approach, with the option to use sudo as an option that could be selected.

While considering the raised issue, another idea also came to mind.  We could define another directive, %include_keys.  The concept would be that rather than include a full access stanza, the included file would only define the key and hmac key for the stanza it is in.  The advantage would be that the administrator could define the allowed ports or user, etc, and the user could set his own keys.  I can implement this if it would be useful.

--Jonathan

**Comment by rabin-io** [comment]
Hi @mrash , added #184 
is that OK ?

**Comment by mrash** [comment]
Yes, that works great. @oneru, I think we should flesh out your %include_keys idea in #184.
