### ISSUE TITLE
How to specify port range

### ISSUE THREAD

**Issue by kassius** [mrash/fwknop#207]
How to specify port range in .fwknoprc? like open UDP 1000-2000? Didn't find it in the docs and as the packet has limited size can't do this inline..

**Comment by mrash** [comment]
Although port ranges are "natively" supported in the SPA packet format, you can specify multiple individual ports (just not a range) with "-A udp/1001,udp/1002". Or, if you know either the minimal port or the maximal port in the range you want, then the command open close cycle feature would provide a path. For example, if the minimal port is 1000, you could define an access.conf stanza with:

CMD_CYCLE_OPEN          /sbin/iptables -A INPUT -s $IP -p $PROTO --dport 1000:$PORT -j ACCEPT
CMD_CYCLE_CLOSE        /sbin/iptables -D INPUT -s $IP -p $PROTO --dport 1000:$PORT -j ACCEPT
CMD_CYCLE_TIMER         30

**Comment by mrash** [comment]
Btw, there is more information on the command cycle feature available in the fwknop tutorial. The example in the tutorial is geared towards ipset integration, but the same concepts apply to other use cases:

http://www.cipherdyne.org/fwknop/docs/fwknop-tutorial.html#spa-with-ipset

**Comment by mrash** [comment]
Closing this issue for now. We may need to consider port ranges for fwknop 3.0.

**Comment by xenithorb** [comment]
I came here specifically looking for port ranges. The application I'm using this for is going to be a public facing webapp that (hopefully) uses fwknopd to punch holes in the firewall so I don't have to worry about the unauthenticated public internet having access to an otherwise targeted service. 

_I was going to_ originally use CMD_CYCLE_OPEN/CLOSE, but the current version in CentOS 7 is 2.6.7 which is one minor version short of that feature. :( Looks like I'm going to have to deploy that upgrade package manually if I want the ability to open up a slew of UDP ports.
