### ISSUE TITLE
client on cygwin: undefined reference to `fko_get_spa_server_auth'

### ISSUE THREAD

**Issue by mlawren** [mrash/fwknop#215]
I'm attempting to build version 2.6.8 under cygwin under 64-bit Windows 8. I only need the client (and it anyway appears that libpcap is not packaged for cygwin) so I'm using `` ./configure --disable-server`.

`make` results in the following error:

```
libtool: link: gcc -g -O2 -Wall -Wformat -Wformat-security -fstack-protector-all -fstack-protector -D_FORTIFY_SOURCE=2 -Wall -Wformat -Wformat-security -fstack-protector-all -fstack-protector -D_FORTIFY_SOURCE=2 -o .libs/fwknop.exe fwknop-fwknop.o fwknop-config_init.o fwknop-spa_comm.o fwknop-utils.o fwknop-http_resolve_host.o fwknop-getpasswd.o fwknop-log_msg.o  ../lib/.libs/libfko.a ../common/libfko_util.a
../common/libfko_util.a(fko_util.o): In function `dump_ctx_to_buffer':
/home/mark/src/fwknop-2.6.8/common/fko_util.c:852: undefined reference to `fko_get_spa_server_auth'
/home/mark/src/fwknop-2.6.8/common/fko_util.c:852:(.text+0xd4f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `fko_get_spa_server_auth'
collect2: error: ld returned 1 exit status
Makefile:458: recipe for target 'fwknop.exe' failed
make[2]: *** [fwknop.exe] Error 1
make[2]: Leaving directory '/home/mark/src/fwknop-2.6.8/client'
Makefile:883: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/mark/src/fwknop-2.6.8'
Makefile:814: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by oneru** [comment]
I've run into strange problems with using stack protection under cygwin/ mingw.  Try  --disable-stack-protector in your ./configure command, and then a make clean and make.

**Comment by oneru** [comment]
Dug a bit more into this.  The stack protection is not the problem.  Current git does compile as expected, but 2.6.8 doesn't seem to compile correctly under Cygwin.  I remember there was some work done on Windows compilation in the past few months, so perhaps this was fixed in one of those commits.  Easiest workaround would be to either compile from git, or use the pre-built fwknop-gui, available here: https://incomsystems.biz/fwknop-gui/downloads.php

**Comment by oneru** [comment]
This issue should be resolved in 2.6.9, which was just released.  Please re-open if you run into this problem again.  Thanks!

**Comment by mlawren** [comment]
Just built and installed fine. Thanks!

-- 
Mark Lawrence

**Comment by mrash** [comment]
Great, thanks for the confirmation.

On Thu, Jun 9, 2016 at 5:19 AM, Mark Lawrence <notifications@github.com>
wrote:

> Just built and installed fine. Thanks!
>
> --
> Mark Lawrence
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrash/fwknop/issues/215#issuecomment-224842696>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAXNROZ96ZrUJd27xsNuqSMGW_hWSlU2ks5qJ9qigaJpZM4IVNlZ>
> .
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by emelsk** [comment]
@mlawren Sorry for bugging and hijacking this older thread, but I'm trying to compile fwknop (client only) myself on Cygwin64 running on Win 7 64-bit, with current/default versions of Cygwin packages (gcc 5.4.0). Using the most straightforward path - export ac_cv_func_realloc_0_nonnull=yes, export ac_cv_func_malloc_0_nonnull=yes, ./autogen.sh, ./configure --disable-server, make, I'm getting binary which segfaults with any command line option other than --help (i.e. fwknop --version segfaults, too). I don't need 'native' Windows build (meaning didn't try use MinGW) as long as the output binary works properly in Cygwin64 environment. I tried to use the 'official' source tarball first (basically meaning skipping the initial autogen.sh step), but the result was exactly the same. Any help would be greatly appreciated.

**Comment by jp-bennett** [comment]
@emelsk I'll take a look at this as soon as I can get to it.

**Comment by mlawren** [comment]
I succeeded with gcc version 5.3.0 so you might try downgrading to that and giving it a go. Otherwise I have no magic insight to offer, sorry.

**Comment by frojasg1** [comment]
Hello, apologies for reopening this thread again, but I have been trying to compile fkwnop 2.6.9 in a cygwin-64 environment (under Windows-10) and I am getting segfaults, as @emelsk told in their message.
I have tried to downgrade gcc to versión 5.3.0, as suggested, and even to 4.9.2 versión, but with the same result: segfaults when executing fwknop client.

Has somebody faced this problem and found any possible solution?

**Comment by mlawren** [comment]
On Sun Feb 18, 2018 at 01:52:43PM +0000, frojasg1 wrote:
> 
> Has somebody faced this problem and found any possible solution?

I have not seen that issue before. To make it easier for the developers
to help I suggest compiling with debugging support (ensure that gcc is
called with "-g") and then running a backtrace with gdb. 

-- 
Mark Lawrence

**Comment by frojasg1** [comment]
Hello,
    Thanks to https://stackoverflow.com/questions/37628530/how-to-debug-using-stackdump-file-in-cygwin I have got some information about the stacktrace of the coredump:

$ cat fwknop.exe.stackdump
Exception: STATUS_ACCESS_VIOLATION at rip=00180195175
rax=00000001802D5E00 rbx=0000000600038B80 rcx=FFFFFFFF802D5E00
rdx=0000000000000040 rsi=0000000000000001 rdi=FFFFFFFF802D5E00
r8 =00000001802D5E08 r9 =0000000000000000 r10=00000001802F9DA8
r11=00000001802D5E00 r12=00000000FFFF7180 r13=00000000FFFF7210
r14=00000000FFFF7AA0 r15=FFFFFFFFFFFFFFFF
rbp=0000000000000000 rsp=00000000FFFF6F58
program=K:\cygwin\usr\local\bin\fwknop.exe, pid 12760, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  00180195175 (0003F89D37F, 00100420750, 0004FBC51B2, 000FFFF76A0)
00000000000  0010040D785 (000FFFFCBF0, 00000000000, 00000000000, 00000000000)
000FFFF8AA0  0010040A6FA (000FFFF7AA0, 000000000DD, 00000000001, 0000000002F)
000FFFF8AA0  001004141DB (00180306610, 0018024D760, 00180053BF1, 000FFFFCCB0)
000FFFFCCB0  00180047BC2 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045863 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045914 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace


$ ldd /usr/local/bin/fwknop.exe
        ntdll.dll => /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffb15070000)
        KERNEL32.DLL => /cygdrive/c/WINDOWS/System32/KERNEL32.DLL (0x7ffb13840000)
        KERNELBASE.dll => /cygdrive/c/WINDOWS/System32/KERNELBASE.dll (0x7ffb11470000)
        cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
        cyggpgme-11.dll => /usr/bin/cyggpgme-11.dll (0x3cccb0000)
        cygssp-0.dll => /usr/bin/cygssp-0.dll (0x3a1390000)
        cygassuan-0.dll => /usr/bin/cygassuan-0.dll (0x3e2750000)
        cyggpg-error-0.dll => /usr/bin/cyggpg-error-0.dll (0x3ccda0000)
        cyggcc_s-seh-1.dll => /usr/bin/cyggcc_s-seh-1.dll (0x3d2230000)
        cygintl-8.dll => /usr/bin/cygintl-8.dll (0x3c07c0000)
        cygiconv-2.dll => /usr/bin/cygiconv-2.dll (0x3c7fb0000)


$ addr2line.exe -a 00180195175 -e /usr/bin/cygwin1.dll
0x0000000180195175
/usr/src/debug/cygwin-2.9.0-3/newlib/libc/string/strnlen.c:45

$ addr2line.exe -a 0010040D785 -e /usr/local/bin/fwknop.exe
0x000000010040d785
/cygdrive/.../fwknop-2.6.9/lib/fko_user.c:105

$ addr2line.exe -a 0010040A6FA -e /usr/local/bin/fwknop.exe
0x000000010040a6fa
/cygdrive.../fwknop-2.6.9/lib/fko_funcs.c:86

$  addr2line.exe -a 001004141DB -e /usr/local/bin/fwknop.exe
0x00000001004141db
/cygdrive/.../fwknop-2.6.9/client/fwknop.c:124

$ addr2line.exe -a 00180047BC2 -e /usr/bin/cygwin1.dll
0x0000000180047bc2
/usr/src/debug/cygwin-2.9.0-3/winsup/cygwin/dcrt0.cc:1018

$ addr2line.exe -a 00180045863  -e /usr/bin/cygwin1.dll
0x0000000180045863
/usr/src/debug/cygwin-2.9.0-3/winsup/cygwin/cygtls.cc:108

$  addr2line.exe -a 00180045914 -e /usr/bin/cygwin1.dll
0x0000000180045914
/usr/src/debug/cygwin-2.9.0-3/winsup/cygwin/exception.h:156


So the complete backtrace that appears in the stackdump is:

0x0000000180195175  /usr/src/debug/cygwin-2.9.0-3/newlib/libc/string/strnlen.c:45
0x000000010040d785  /cygdrive/.../fwknop-2.6.9/lib/fko_user.c:105
0x000000010040a6fa  /cygdrive.../fwknop-2.6.9/lib/fko_funcs.c:86
0x00000001004141db  /cygdrive/.../fwknop-2.6.9/client/fwknop.c:124
0x0000000180047bc2  /usr/src/debug/cygwin-2.9.0-3/winsup/cygwin/dcrt0.cc:1018
0x0000000180045863  /usr/src/debug/cygwin-2.9.0-3/winsup/cygwin/cygtls.cc:108
0x0000000180045914  /usr/src/debug/cygwin-2.9.0-3/winsup/cygwin/exception.h:156


But I do not know if that make sense, because I have not been able to open exception.h file.


Please, let me know if this issue can be solved.

**Comment by jp-bennett** [comment]
@frojasg1 Try using the command line option to spoof the username. Something like "-U spoof" and see if that gets you past the problem.

**Comment by frojasg1** [comment]
Still Segmentation fault, with exactly the same backtrace.

$ ./xxxxxxxxxx.sh
./xxxxxxxxxxx.sh: línea 7: 12576 Segmentation fault      (`core' generado) fwknop -U spoof -A tcp/22,tcp/80,tcp/3000,tcp/16000 -R -D xx.xx.xx.xx --use-hmac --key-base64-rijndael=TDRfcGFzU1dvUjdtM2ojcmZ3a25vcAo= --key-base64-hmac=MF90cjRfX3BhU3NXMHJELmQxZjNyRU5UZVBhcjQ/SG1BQy4uCg== -v -p xxxxx -f 120






$ cat fwknop.exe.stackdump
Exception: STATUS_ACCESS_VIOLATION at rip=00180195175
rax=00000001802D5E00 rbx=0000000600038B80 rcx=FFFFFFFF802D5E00
rdx=0000000000000040 rsi=0000000000000001 rdi=FFFFFFFF802D5E00
r8 =00000001802D5E08 r9 =0000000000000000 r10=00000001802F9DA8
r11=00000001802D5E00 r12=00000000FFFF7170 r13=00000000FFFF7200
r14=00000000FFFF7A90 r15=FFFFFFFFFFFFFFFF
rbp=0000000000000000 rsp=00000000FFFF6F48
program=K:\cygwin\usr\local\bin\fwknop.exe, pid 12576, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  00180195175 (0006A031E1C, 00100420750, 00079E38235, 000FFFF7690)
00000000000  0010040D785 (000FFFFCBE0, 00000000000, 00000000000, 00000000000)
000FFFF8A90  0010040A6FA (000FFFF7A90, 000000000E6, 00000000001, 0000000002F)
000FFFF8A90  001004141DB (001801891FA, 0018005A734, 00180306660, 0018024D760)
000FFFFCCB0  00180047BC2 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045863 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045914 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

**Comment by jp-bennett** [comment]
@frojasg1 Still looking into this, but a quick note, You have your access keys unredacted there.

**Comment by frojasg1** [comment]
They are obsolete :)

**Comment by jp-bennett** [comment]
@mrash @dstuart I've narrowed down the issue to the cuserid() function in lib/fko_user.c.  When compiling, this warning is shown:

`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I ../common -g -O2 -Wall -Wformat -Wformat-security -fstack-protector-all -fstack-protector -fPIC -D_FORTIFY_SOURCE=2 -MT fko_user.lo -MD -MP -MF .deps/fko_user.Tpo -c fko_user.c  -DDLL_EXPORT -DPIC -o .libs/fko_user.o
fko_user.c: In function ‘fko_set_username’:
fko_user.c:84:24: warning: implicit declaration of function ‘cuserid’ [-Wimplicit-function-declaration]
             username = cuserid(NULL);
                        ^~~~~~~
fko_user.c:84:22: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
             username = cuserid(NULL);
                      ^
`
Under cygwin cuserid is returning a garbage pointer.  The getlogin() function works as expected.  It's unclear to me whether _XOPEN_SOURCE is being set incorrectly, or if cuserid is simply a broken implementation.  This is really a new issue, so rather than reopen this one, I'll create a new issue.

**Comment by frojasg1** [comment]
Thank you very much for the speed :)

For me it is important to have access to fwknop via cygwin and I will be looking forward the solution.

**Comment by jp-bennett** [comment]
@frojasg1 I've replicated the error, and we'll get it fixed.  For now, you *can* work around it by including a SPOOF_USER environment variable on the command line.  So call fwknop like this:

 SPOOF_USER="spoof" fwknop -A tcp/22...

That function is dying during initialization, before the arguments are read in, but it does check for the environment variable.  That should get you up and running for now.

**Comment by frojasg1** [comment]
wow, it worked !!

Thank you very much !!
