### ISSUE TITLE
[Android/Capture qr] Error calling Barcode Scanner

### ISSUE THREAD

**Issue by mlawren** [mrash/fwknop#231]
Version 1.2.1 of the Fwknop2 application running under Android 6.0.1 (Cyanogenmod) on a Wileyfox Swift.

Selecting the "Capture qr" action from either an existing or a new config entry results in the error message: "Barcode Scanner: Sorry, the Android camera encountered a problem. You may need to restart the device."

If I start the Barcode Scanner application manually it works fine, so there appears to be an issue with how it is started from Fwknop2.

**Comment by mlawren** [comment]
Related to the above: I tried to paste the captured text anyway into Fwknop2 but a long-press on the key/hmac fields does nothing. I presume this is so that the keys can't be copied. Perhaps this restriction could be relaxed for new configuration entries? Or paste-only allowed (don't know if Android supports that).

**Comment by jp-bennett** [comment]
I suspect the camera issue is permissions related.  There is a beta at https://play.google.com/apps/testing/org.cipherdyne.fwknop2 and I think the issue is solved there.  

I am very surprised that the paste option is missing, though that may be corrected in the Beta as well.  Let me know if either of these are problems there and I'll be sure to address.

**Comment by mlawren** [comment]
The QR code issue appears to be solved in the latest version, as is pasting into the key fields.

Many thanks for your work!
