### ISSUE TITLE
Knock Not Opening Port

### ISSUE THREAD

**Issue by primesoftware** [mrash/fwknop#253]
Hello all,
I've setup fwknop once before and have it working on my Raspberry Pi, but I would like to move that task off to my newly built Arch Linux router. Fwknop installed correctly and I've got it running. The problem is when I send the packet from the client the rule does not get added. I am running fwknop on the WAN side. Here are my iptables rules:

`
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [2:168]
:FWKNOP_INPUT - [0:0]
:TCP - [0:0]
:UDP - [0:0]

-A INPUT -j FWKNOP_INPUT
-A INPUT -i lan0 -s 172.16.0.0/21 -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -p icmp --icmp-type any -j ACCEPT
-A INPUT -p udp -m conntrack --ctstate NEW -j UDP
-A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP
-A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
-A INPUT -p tcp -j REJECT --reject-with tcp-reset
-A INPUT -j REJECT --reject-with icmp-proto-unreachable
-A TCP -i lan0 -p tcp -j ACCEPT
-A UDP -i lan0 -p udp -j ACCEPT
-A FORWARD -i lan0 -o wan0 -j ACCEPT
-A FORWARD -i wan0 -o lan0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT

*nat
:PREROUTING ACCEPT [10:1294]
:INPUT ACCEPT [7:588]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o wan0 -j MASQUERADE
COMMIT

*mangle
:PREROUTING ACCEPT [21:1938]
:INPUT ACCEPT [21:1938]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [8:672]
:POSTROUTING ACCEPT [8:672]
COMMIT

*raw
:PREROUTING ACCEPT [21:1938]
:OUTPUT ACCEPT [8:672]
COMMIT

*security
:INPUT ACCEPT [10:744]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [8:672]
COMMIT
`
I tried both with and without rules to explicitly permit the udp port that PCAP is sniffing on, but no difference. I do see a lot of "Did not find expire comment in rules list 0" errors when I start from commandline without forking, but it does not appear to stop the program from running. All configs are defaults with the exception that I changed the port udp PCAPs on. In fact they are copies from my working machine. Any ideas?

Thanks!

**Comment by mrash** [comment]
Do you see any messages like "Warning: Could not use the 'comment' match"? If so, then the kernel on the Arch Linux box has not been compiled with iptables 'comment' match support. That is fine - just switch over to using the fwknop 'command cycle' feature. Some material on this can be found here: http://www.cipherdyne.org/fwknop/docs/fwknop-tutorial.html#spa-with-ipset

Basically you would just need an access.conf stanza like this:

SOURCE            ANY
KEY_BASE64        <base64 string>
HMAC_KEY_BASE64   <base64 string>
CMD_CYCLE_OPEN    /sbin/iptables -A INPUT -s $SRC -p $PROTO --dport $PORT -j ACCEPT
CMD_CYCLE_CLOSE   iptables -D INPUT -s $SRC -p $PROTO --dport $PORT -j ACCEPT

If you want to use the 'FWKNOP_INPUT' chain, that is fine too, but you would need to manually maintain the jump rule from the INPUT chain to the FWKNOP_INPUT. That is because the command cycle feature is meant as a generic interface to the underlying system, so it doesn't know anything about iptables chains or any structure outside of $SRC, $PROTO, etc. variable substitutions.

**Comment by mrash** [comment]
Oh, minor correction to the above - the CMD_CYCLE_OPEN variable should set an 'early' rule number in the INPUT chain like this:

CMD_CYCLE_OPEN /sbin/iptables -A INPUT 1 -s $SRC -p $PROTO --dport $PORT -j ACCEPT

**Comment by primesoftware** [comment]
@mrash I will give that a try and see what happens. Just curious though about the sniffer. Do I have to have the UDP port open on the firewall for the sniffer to work?

**Comment by mrash** [comment]
If you are running in the default sniffer mode (i.e. not --udp-server on the fwknopd command line), then you don't need to have the UDP port open. If you switch to --udp-server, then you will need the port open.

**Comment by primesoftware** [comment]
@mrash I've added those ops in the access.conf along with CMD_CYCLE_TIMER but still no luck. Is there anyway to test if the SPA packet is being "sniffed" or received? Also, I am not running with the --udp-server option. I am running the fwknopd.service on Arch Linux.

**Comment by mrash** [comment]
If you want to see if the SPA packed is received, one way is to just run fwknopd from the command line with the '-f' arg. Usually something like this will work:

fwknopd -i eth0 -f -v

Then send the SPA packet from the client and you should see something in the output.

**Comment by primesoftware** [comment]
Ok, so I made some progress. I just wasn't having any luck with UDP so I switched to TCP and now the above command at least shows activity when I send the packs. The problem is I am now getting the following:

SPA data time difference is too great (14754 seconds).

This is strange because it definitely doesn't take that long to register.

**Comment by jp-bennett** [comment]
On 07/19/2017 12:12 AM, primesoftware wrote:
> Ok, so I made some progress. I just wasn't having any luck with UDP so I switched to TCP and now the above command at least shows activity when I send the packs. The problem is I am now getting the following:
> 
> SPA data time difference is too great (14754 seconds).
> 
> This is strange because it definitely doesn't take that long to register.

This usually indicates that the system clock on the two machines are different.  That's just over 4 hours, so could mean there is a time-zone issue as well.  The Fwknop client has an option to insert correction to the time stamp.

"""
--time-offset-plus=<time>

By default, the fwknopd daemon on the server side enforces time synchronization between the clocks running on client and server systems. The fwknop client places the local time within each SPA packet as a time stamp to be validated by the fwknopd
server after decryption. However, in some circumstances, if the clocks are out of sync and the user on the client system does not have the required access to change the local clock setting, it can be difficult to construct and SPA packet with a time
stamp the server will accept. In this situation, the --time-offset-plus option can allow the user to specify an offset (e.g. "60sec" "60min" "2days" etc.) that is added to the local time.
--time-offset-minus=<time>

This is similar to the --time-offset-plus option (see above), but subtracts the specified time offset instead of adding it to the local time stamp.
"""

You might try sending packets with an option like --time-offset-plus=14754sec or --time-offset-minus=14754sec

**Comment by primesoftware** [comment]
@jp-bennett You hit the nail on the head. My hardware clock time was off by 4 hours. That has since been fixed and I am able to get things working over TCP.

I am still baffled by the UDP issue though. It is almost as if my ISP is blocking all UDP traffic. I am using tcpdump to see what comes in on the wan side and it is not registering any UDP traffic even when I use netcat. This is strange since up until a week ago when I was using fwknop on my Raspberry Pi it was working fine with UDP. I thought maybe there is some kernel setting ignoring UDP traffic, but according to tcpdump the kernel isn't dropping anything. It is very bizarre.

The only thing that has really changed in my setup is I now have an Arch Linux box acting as a router instead of my FiOS Quantum Gateway.

**Comment by mrash** [comment]
You might try switch the UDP port to 53. If your ISP is actually blocking some UDP ports, then there is a greater likelihood that they aren't blocking 53. Also, on your tcpdump command line (if you aren't already doing this), it is usually a good idea to stop any resolutions and also to make it line-buffered just to make sure you get the 'rawest' data possible:

tcpdump -i eth0 -l -nn -s 0

If you do switch to port 53, you'll need to update the PCAP_FILTER statement in the fwknopd.conf file.

**Comment by primesoftware** [comment]
@mrash OK, so I don't think the ISP is at fault here. I tried to capture UDP packets on the lan side which I can permit and tcpdump on the router doesn't see UDP packets on this interface either......very bizarre!

**Comment by primesoftware** [comment]
Ok, so I FINALLY fixed this problem....well problemS actually. So netcat apparently doesn't send blank UDP packets so the reason I wasn't receiving any packets was because I wasn't sending them in the first place, duh! The port knocker was working fine on UDP, but it just wasn't receiving anything. Problem 2 was my cell phone was not time synced (off by 5 minutes), so the port knocker rejected it as it is designed to do. Problem 3 was as @mrash said above my kernel did not have comment match compiled in so I am just using the command cycle syntax which works just as good for me. Ugh what a mess......thanks for the help guys!
