### ISSUE TITLE
fwknop client on ubuntu throws `error in getaddrinfo: Name or service not known`

### ISSUE THREAD

**Issue by winteraz** [mrash/fwknop#262]
fwknop client fails on ubuntu 17
```

echo XXX | fwknop -A tcp/22 --stdin -a 24.11.11.11 -D  -v 
error in getaddrinfo: Name or service not known
send_spa_packet: packet not sent.

$ uname -rv
4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
```

**Comment by jp-bennett** [comment]
@winteraz I suspect it's complaining because you don't have a destination address after the "-D" option.  You'll want to provide the remote server's IP address or hostname there.  So if you're trying to send a packet to a machine at 8.8.8.8, your command would be:
echo XXX | fwknop -A tcp/22 --stdin -a 24.11.11.11 -D 8.8.8.8 -v

**Comment by winteraz** [comment]
That was the issue indeed...Sorry for posting such a silly 'bug'.  Fwknop is very a useful and awesome piece of software.
