### ISSUE TITLE
Feature Request: allow tailoring of the iptables command

### ISSUE THREAD

**Issue by waitfor1t** [mrash/fwknop#264]
The current implementation is fixed to using -s <source IP> in the IP tables ALLOW command, where the source IP is where the initial packet comes from. HOWEVER: the application traffic may come from a different IP than the SPA packet. Example would be knocking from phone app to use SSH from laptop. Another: mobile phone carrier constantly switches IP, so SPA will come from one IP, and application traffic (ie: SSH) will come from another IP.  AT&T, one of the largest wireless carriers in the US does this, making the mobile app useless. If we could tailor the command, -s could be optional.

**Comment by jp-bennett** [comment]
Fwknop does have the ability to include an IP to allow inside the SPA packet.  In this case, the specified IP address is used as the SOURCE ip in the iptables rule.

Are you using the mobile app available on the play store/fdroid, source at https://github.com/jp-bennett/Fwknop2 ?

If you edit a specific config, there should be an option labeled "Allowed IP".  The selection to resolve IP will use an https request to detect the phones' effective IP address, allowing it to work over mobile networks.  Another selection, "prompt IP" will ask for an IP every time.  This is intended for the case where you're sending an SPA packet from the phone on behalf of another device, like a laptop.  There is even an option, when prompted for an IP, to capture a qr code from qr.incom.co.  Pull that site (that I provide) up on the laptop, and use the qr code within the fwknop app when prompted.  It will extract the Ip address of the laptop, and send the SPA packet with that as the IP to allow.

From the command line client, instead of using the -s switch, the -R switch will try to resolve your public IP over https, while the -a switch allows you to specify the IP address to use.

**Comment by waitfor1t** [comment]
I am using the mobile app. 
The IP address resolves differently every time from the mobile app. I see the SPA packet coming in from one address, and the rule added for another address. In addition, the application appears to be coming from yet another IP. I want my firewall rule to optionally allow traffic from ANY ip once opened.

**Comment by jp-bennett** [comment]
Ah, that's interesting.  You can use the open/close cycle to write custom iptables rules:  http://cipherdyne.org/blog/2015/12/single-packet-authorization-and-third-party-devices.html

That should allow you to write a rule to open a port to all IP addresses.

**Comment by waitfor1t** [comment]
That's exactly what I was looking for! WOOT. will try. Thanks for being polite with my RTFM moment. :)

**Comment by jp-bennett** [comment]
Cool, glad that works for you!

**Comment by waitfor1t** [comment]
For whatever reason the version 2.6.9 I have does not like CMD_CYCLE_CLOSE, so the option forces me to essentially duplicate the timer function implemented to expire rules, or fork-n-fix, or recompile a newer version. So: right solution, but bug encountered. :) Ugh.

**Comment by waitfor1t** [comment]
I solved this by making CMD_CYCLE_OPEN dual-purpose.  knock once to open, and then knock again to close. This starts and stops the myprog service. If there's no responding service, then the ports will be essentially dead, which for my purposes is just as good as opening/closing the ports.
#!/bin/sh
# starts/stops myprog. Used by the port knocker.

if pidof myprog > 0; then
  /etc/init.d/myprog stop
  logger Fwknop stopped myprog.
else
  /etc/init.d/myprog start
  logger Fwknop started myprog.
fi
